apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "buildbuddy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
data:
  {{- /* Make a deep enough copy of the default config */}}
  {{- $c := dict }}
  {{- range $key, $dictVal := .Values.config }}
  {{- $dictCopy := merge (dict) $dictVal }}
  {{- $_ := set $c $key $dictCopy }}
  {{- end }}

  {{- /* Update the copied default config based on .Values */}}

  {{- if not .Values.config.executor.appTarget }}
  {{- $_ := set $c.executor "app_target" (print "grpc://buildbuddy-enterprise:1985") }}
  {{- end }}
  
  {{- /* Render the processed config as an encoded YAML string */}}
  {{- /* NOTE: Mounted at /config.yaml on the buildbuddy pod */}}
  config.yaml: {{ $c | toYaml | b64enc }}
