dependencies:
  - name: mysql
    version: 1.6.4
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: buildbuddy-redis
    alias: redis
    version: 0.0.4
    repository: https://helm.buildbuddy.io
    condition: redis.enabled
  - name: ingress-nginx
    alias: ingress
    version: 2.3.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: cert-manager
    alias: certmanager
    version: 0.16.1
    repository: https://charts.jetstack.io
    condition: ingress.enabled
  - name: buildbuddy-executor
    alias: executor
    version: 0.0.16
    repository: https://helm.buildbuddy.io
    condition: executor.enabled
