dependencies:
  - name: mysql
    version: 1.6.4
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: buildbuddy-redis
    alias: redis
    version: 0.0.9
    repository: https://helm.buildbuddy.io
    condition: redis.enabled
  - name: ingress-nginx
    alias: ingress
    version: 4.0.16
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.controller.enabled,ingress.enabled
  - name: cert-manager
    alias: certmanager
    version: 1.6.1
    repository: https://charts.jetstack.io
    condition: certmanager.enabled
  - name: buildbuddy-executor
    alias: executor
    version: 0.0.105 # Executor chart version
    repository: https://helm.buildbuddy.io
    condition: executor.enabled
  - name: metrics-server
    version: 5.11.9
    repository: https://charts.bitnami.com/bitnami
    condition: prometheus.enabled
  - name: prometheus
    version: 13.3.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: prometheus-adapter
    version: 2.12.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.6.2
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
