dependencies:
  - name: metrics-server
    version: 6.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: prometheus.enabled
  - name: prometheus
    version: 15.14.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: prometheus-adapter
    version: 3.4.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
