dependencies:
- name: mysql
  version: 1.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: mysql.enabled
- name: ingress-nginx
  alias: ingress
  version: 2.3.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress.enabled
- name: cert-manager
  alias: certmanager
  version: 0.16.1
  repository: https://charts.jetstack.io
  condition: ingress.enabled
