apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildbuddy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
data:
  redis-config-file: |
    maxmemory {{ .Values.maxMemory }}
    maxmemory-policy allkeys-lru
                
