{{ if .Values.ingress.enabled }}
apiVersion: {{ include "buildbuddy.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "buildbuddy.fullname" . }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/backend-protocol: "grpc"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      grpc_next_upstream error timeout http_502 non_idempotent;
      grpc_next_upstream_tries 3;
    {{- if .Values.ingress.sslEnabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | default "letsencrypt-prod"}}
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.grpcHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "buildbuddy.name" . }}
          servicePort: grpc
  {{ if .Values.ingress.sslEnabled }}
  tls:
    - secretName: {{ .Values.ingress.grpcHost }}-tls
      hosts:
        - {{ .Values.ingress.grpcHost }}
  {{ end }}
---
apiVersion: {{ include "buildbuddy.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "buildbuddy.fullname" . }}-http
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- if .Values.ingress.sslEnabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | default "letsencrypt-prod"}}
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.httpHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "buildbuddy.name" . }}
          servicePort: http
  {{ if .Values.ingress.sslEnabled }}
  tls:
    - secretName: {{ .Values.ingress.httpHost }}-tls
      hosts:
        - {{ .Values.ingress.httpHost }}
  {{ end }}
{{ end }}
